
  /**
  * Generated by @proofgeist/fmdapi package
  * https://github.com/proofgeist/fmdapi
  * DO NOT EDIT THIS FILE DIRECTLY. Changes may be overritten
  */
  import { z } from "zod";

  // @generated
  // prettier-ignore
  /* eslint-disable */
  export const ZInbox = z.object({
      "CreatedBy": z.string(),
      "CreationTimestamp": z.string(),
      "inboxPayload": z.string(),
      "ModificationTimestamp": z.string(),
      "ModifiedBy": z.string(),
      "ONE": z.union([z.string(), z.number()]),
      "PrimaryKey": z.string(),
      "scriptName": z.string(),
      "scriptResult": z.string(),
      "ScriptStartTimestamp": z.string(),
  });

  export type TInbox = z.infer<typeof ZInbox>;
