
  /**
  * Generated by @proofgeist/fmdapi package
  * https://github.com/proofgeist/fmdapi
  * DO NOT EDIT THIS FILE DIRECTLY. Changes may be overritten
  */
  import { z } from "zod";

  // @generated
  // prettier-ignore
  /* eslint-disable */
  export const Ztimecardline = z.object({
      "__id": z.string(),
      "hrsUnworked": z.string(),
      "time_in": z.string(),
      "time_out": z.string(),
      "hrsWorked_c": z.string(),
      "TCL_EVS__EventSchedule::vl_display_evs_c": z.string(),
      "TCL_CJT__ContractJobTitle::Name": z.string(),
      "display_modifiers_c": z.string(),
  });

  export type Ttimecardline = z.infer<typeof Ztimecardline>;
